name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  publicaddr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ "3.11", "3.12", "3.13", "3.14"  ]

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        python --version
        python -m pip install -r requirements.txt
        python -m unittest tests.test_google -v
        python -m unittest tests.test_akamai -v
        python -m unittest tests.test_cloudflare -v
        python -m unittest tests.test_opendns -v
        python -m unittest tests.test_ipify -v
        python -m unittest tests.test_icanhazip -v
        python -m unittest tests.test_ifconfigme -v
        python -m unittest tests.test_matrix -v
        python -m unittest tests.test_framasoft -v
      env:
        PUBLICADDR_IPV6_ENABLED: 0
