name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  publicaddr:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python: [ "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        python --version
        python -m pip install -r requirements.txt
        python -m unittest tests.test_google
        python -m unittest tests.test_akamai
        python -m unittest tests.test_cloudflare
        python -m unittest tests.test_opendns
