name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  publicaddr:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python: [ "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m unittest tests.test_google.TestGoogle.test_get_ip4
        sudo python3 -m unittest tests.test_akamai.TestAkamai.test_get_ip4
        sudo python3 -m unittest tests.test_cloudflare.TestCloudflare.test_get_ip4
        sudo python3 -m unittest tests.test_opendns.TestOpenDNS.test_get_ip4